baseURL = "https://listen-to-euterpe.eu/"
languageCode = "en-us"
title = "Euterpe Music"
theme = "syna"
enableGitInfo = true

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/about"
  name = "About"
  weight = 20

[[menu.main]]
  url = "/demo"
  name = "Demo"
  weight = 25

[[menu.main]]
  url = "/screenshots"
  name = "Screenshots"
  weight = 28

[[menu.main]]
  url = "/clients"
  name = "Clients"
  weight = 30

[[menu.main]]
  url = "/blog"
  name = "Blog"
  weight = 40

[[menu.main]]
  url = "/docs"
  name = "Docs"
  weight = 50

[[menu.footer]]
  url = "https://github.com/ironsmile/euterpe-rhythmbox"
  name = "Euterpe for Rhythmbox"
  weight = 10

[[menu.footer]]
  url = "https://github.com/ironsmile/euterpe-mobile"
  name = "Euterpe Mobile Apps"
  weight = 20

[[menu.footer]]
  url = "https://doycho.com"
  name = "Doycho's Personal Corner"
  weight = 30

[[menu.footer]]
  url = "https://github.com/ironsmile/euterpe-website"
  name = "This website's source"
  weight = 40

[[menu.copyright_footer]]
  url = "/about"
  name = "About"
  weight = 10

[[menu.copyright_footer]]
  url = "/clients"
  name = "Clients"
  weight = 30

[[menu.footer_social]]
  weight = 20
  name = "Euterpe GitHub repository"
  pre = "fab fa-github"
  url = "https://github.com/ironsmile/euterpe"
